name: meri github wali pipeline
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: terraform init and plan
    runs-on: self-hosted
    environment: dev 
    steps: 
    - name: Checkout
      uses: actions/checkout@v5.0.0
     
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: be0eefc5-50d3-4280-a8cd-66a3c2586ce1
        tenant-id: efeb520c-f48c-485c-95c5-be148c93599f
        subscription-id: c05900c4-9a99-417d-878e-413b907a6035

    - name: terraform init
      run: terraform init
      working-directory: environment/dev

    - name: terraform plan
      run: terraform plan 
      working-directory: environment/dev
  
  deploy:
    name: terraform apply
    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    environment: dev
    steps: 
    - name: Checkout
      uses: actions/checkout@v5.0.0
     
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: be0eefc5-50d3-4280-a8cd-66a3c2586ce1
        tenant-id: efeb520c-f48c-485c-95c5-be148c93599f
        subscription-id: c05900c4-9a99-417d-878e-413b907a6035
    
    - name: terraform init
      run: terraform init
      working-directory: environment/dev    
    - name: terraform apply 
      run: terraform apply --auto-approve
      working-directory: environment/dev
       
        
        
      
       
          
