name: meri github wali pipeline

on: workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  terraform-init-plan:
    name: terraform init and plan
    runs-on: self hosted
    steps: 
    - name: Checkout
      uses: actions/checkout@v5.0.0
     
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: c9f16b78-a14d-46c8-b2bd-b2f9ebb633a1
        tenant-id: efeb520c-f48c-485c-95c5-be148c93599f
        subscription-id: c05900c4-9a99-417d-878e-413b907a6035

    -name: terraform init
     run: terraform init
     working-directory: environment/dev

    -name: terraform plan
     run: terraform plan 
     working-directory: environment/dev
      
       
       
        
        
      
       
          
